# Part 1

Crossing the bridge, you've barely reached the other side of the stream when a program comes up to you, clearly in distress. "It's my child process," she says, "he's gotten lost in an infinite grid!"

Fortunately for her, you have plenty of experience with infinite grids.

Unfortunately for you, it's a hex grid.

The hexagons ("hexes") in this grid are aligned such that adjacent hexes can be found to the north, northeast, southeast, south, southwest, and northwest:

```
  \ n  /
nw +--+ ne
  /    \
-+      +-
  \    /
sw +--+ se
  / s  \
```

You have the path the child process took. Starting where he started, you need to determine the fewest number of steps required to reach him. (A "step" means to move from the hex you are in to any adjacent hex.)

For example:

- `ne,ne,ne` is 3 steps away.
- `ne,ne,sw,sw` is 0 steps away (back where you started).
- `ne,ne,s,s` is 2 steps away (`se,se`).
- `se,sw,se,sw,sw` is 3 steps away (`s,s,sw`).

In [1]:
from functools import reduce
from operator import add

import numpy as np
import numpy.testing as npt

In [2]:
def pzl_input():
    with open('./inputs/day11/input.txt') as f:
        return f.read().strip().split(',')

In [3]:
moves = {
    'nw': np.int_([-1, 1]),
    'n': np.int_([0, 2]),
    'ne': np.int_([1, 1]),
    'se': np.int_([1, -1]),
    's': np.int_([0, -2]),
    'sw': np.int_([-1, -1])
}

In [22]:
def follow_path(path: list) -> np.array:
    """Returns the final position after following a list of moves"""
    final_pos = reduce(add, (moves[dir_] for dir_ in path), np.int_([0, 0]))
    return final_pos

In [5]:
npt.assert_array_equal(follow_path([]), np.int_([0, 0]))
npt.assert_array_equal(follow_path('ne,ne,ne'.split(',')), np.int_([3, 3]))
npt.assert_array_equal(follow_path('ne,ne,sw,sw'.split(',')), np.int_([0, 0]))
npt.assert_array_equal(follow_path('ne,ne,s,s'.split(',')), np.int_([2, -2]))
npt.assert_array_equal(follow_path('se,sw,se,sw,sw'.split(',')), np.int_([-1, -5]))

In [16]:
def shortest_path(pos: np.array) -> int:
    x, y = np.absolute(pos)
    if y <= x:
        return x
    else:
        return x + (y - x) // 2

In [19]:
assert shortest_path(np.int_([0, 0])) == 0
assert shortest_path(np.int_([5, 0])) == 5
assert shortest_path(np.int_([0, 4])) == 2
assert shortest_path(np.int_([4, 4])) == 4
assert shortest_path(np.int_([3, 3])) == 3
assert shortest_path(np.int_([-5, -3])) == 5
assert shortest_path(np.int_([5, -3])) == 5
assert shortest_path(np.int_([-3, 3])) == 3

assert shortest_path(np.int_([1, 5])) == 3
assert shortest_path(np.int_([0, 4])) == 2
assert shortest_path(np.int_([0, 4])) == 2
assert shortest_path(np.int_([2, 4])) == 3
assert shortest_path(np.int_([3, 5])) == 4
assert shortest_path(np.int_([3, 11])) == 7

In [20]:
assert shortest_path(follow_path([])) == 0
assert shortest_path(follow_path('ne,ne,ne'.split(','))) == 3
assert shortest_path(follow_path('ne,ne,sw,sw'.split(','))) == 0
assert shortest_path(follow_path('ne,ne,s,s'.split(','))) == 2
assert shortest_path(follow_path('se,sw,se,sw,sw'.split(','))) == 3

In [21]:
shortest_path(follow_path(pzl_input()))

824

In [10]:
follow_path(pzl_input())

array([ -437, -1211])

# Part 2

How many steps away is the furthest he ever got from his starting position?

In [25]:
from itertools import accumulate
from operator import add

In [31]:
# recipe for getting every position along a path
list(accumulate((moves[dir_] for dir_ in 'se,sw,se,sw,sw'.split(',')), add))

[array([ 1, -1]),
 array([ 0, -2]),
 array([ 1, -3]),
 array([ 0, -4]),
 array([-1, -5])]

In [30]:
max(shortest_path(pos) for pos in accumulate((moves[dir_] for dir_ in pzl_input()), add))

1548