# Part 1

Suddenly, the GPU contacts you, asking for help. Someone has asked it to simulate too many particles, and it won't be able to finish them all in time to render the next frame at this rate.

It transmits to you a buffer (your puzzle input) listing each particle in order (starting with particle 0, then particle 1, particle 2, and so on). For each particle, it provides the X, Y, and Z coordinates for the particle's position (p), velocity (v), and acceleration (a), each in the format `<X,Y,Z>`.

Each tick, all particles are updated simultaneously. A particle's properties are updated in the following order:

- Increase the X velocity by the X acceleration.
- Increase the Y velocity by the Y acceleration.
- Increase the Z velocity by the Z acceleration.
- Increase the X position by the X velocity.
- Increase the Y position by the Y velocity.
- Increase the Z position by the Z velocity.

Because of seemingly tenuous rationale involving z-buffering, the GPU would like to know which particle will stay closest to position `<0,0,0>` in the long term. Measure this using the Manhattan distance, which in this situation is simply the sum of the absolute values of a particle's X, Y, and Z position.

For example, suppose you are only given two particles, both of which stay entirely on the X-axis (for simplicity). Drawing the current states of particles 0 and 1 (in that order) with an adjacent a number line and diagram of current X positions (marked in parenthesis), the following would take place:

```
p=< 3,0,0>, v=< 2,0,0>, a=<-1,0,0>    -4 -3 -2 -1  0  1  2  3  4
p=< 4,0,0>, v=< 0,0,0>, a=<-2,0,0>                         (0)(1)

p=< 4,0,0>, v=< 1,0,0>, a=<-1,0,0>    -4 -3 -2 -1  0  1  2  3  4
p=< 2,0,0>, v=<-2,0,0>, a=<-2,0,0>                      (1)   (0)

p=< 4,0,0>, v=< 0,0,0>, a=<-1,0,0>    -4 -3 -2 -1  0  1  2  3  4
p=<-2,0,0>, v=<-4,0,0>, a=<-2,0,0>          (1)               (0)

p=< 3,0,0>, v=<-1,0,0>, a=<-1,0,0>    -4 -3 -2 -1  0  1  2  3  4
p=<-8,0,0>, v=<-6,0,0>, a=<-2,0,0>                         (0)   
```

At this point, particle 1 will never be closer to `<0,0,0>` than particle 0, and so, in the long run, particle 0 will stay closest.

Which particle will stay closest to position `<0,0,0>` in the long term?

In [23]:
import itertools
import re
from io import StringIO
from textwrap import dedent
from typing import Tuple, Dict, Set

import numpy as np
from dataclasses import dataclass

In [2]:
@dataclass
class Point:
    id_: int
    pos: Tuple[int]
    vel: Tuple[int]
    acc: Tuple[int]

In [3]:
def process_points(rows):
    points = []
    for i, row in enumerate(rows):
        p, v, a = (
            tuple(int(x) for x in item.group(0)[1:-1].split(',')) 
            for item in re.finditer(r'\<(.+?)\>', row))
        points.append(Point(i, p, v, a))
    return points

In [4]:
def _test_input():
    return process_points(StringIO(dedent("""\
        p=< 3,0,0>, v=< 2,0,0>, a=<-1,0,0>
        p=< 4,0,0>, v=< 0,0,0>, a=<-2,0,0>
        """)))
TEST_INPUT = _test_input()

In [5]:
def _puzzle_input():
    with open('./inputs/day20/input.txt') as f:
        return process_points(f)
PUZZLE_INPUT = _puzzle_input()

In [6]:
def pos_at_t(point: Point, time_arr: np.array) -> Tuple[int]:
    return tuple(point.pos[i] + (point.acc[i] * time_arr + point.vel[i]).sum() for i in range(3))

In [8]:
assert pos_at_t(TEST_INPUT[0], np.arange(1, 2)) == (4, 0, 0)
assert pos_at_t(TEST_INPUT[0], np.arange(1, 3)) == (4, 0, 0)
assert pos_at_t(TEST_INPUT[0], np.arange(1, 4)) == (3, 0, 0)

assert pos_at_t(TEST_INPUT[1], np.arange(1, 2)) == (2, 0, 0)
assert pos_at_t(TEST_INPUT[1], np.arange(1, 3)) == (-2, 0, 0)
assert pos_at_t(TEST_INPUT[1], np.arange(1, 4)) == (-8, 0, 0)

In [9]:
time_arr = np.arange(1, 100 + 1)
assert min(TEST_INPUT, key=lambda p: sum(abs(x) for x in pos_at_t(p, time_arr))).id_ == 0

In [10]:
time_arr = np.arange(1, 100000 + 1)
min(PUZZLE_INPUT, key=lambda p: sum(abs(x) for x in pos_at_t(p, time_arr)))

Point(id_=308, pos=(2978, 2082, 4280), vel=(-135, -88, -178), acc=(1, 0, 0))

# Part 2

To simplify the problem further, the GPU would like to remove any particles that collide. Particles collide if their positions ever exactly match. Because particles are updated simultaneously, more than two particles can collide at the same time and place. Once particles collide, they are removed and cannot collide with anything else after that tick.

For example:

```
p=<-6,0,0>, v=< 3,0,0>, a=< 0,0,0>    
p=<-4,0,0>, v=< 2,0,0>, a=< 0,0,0>    -6 -5 -4 -3 -2 -1  0  1  2  3
p=<-2,0,0>, v=< 1,0,0>, a=< 0,0,0>    (0)   (1)   (2)            (3)
p=< 3,0,0>, v=<-1,0,0>, a=< 0,0,0>

p=<-3,0,0>, v=< 3,0,0>, a=< 0,0,0>    
p=<-2,0,0>, v=< 2,0,0>, a=< 0,0,0>    -6 -5 -4 -3 -2 -1  0  1  2  3
p=<-1,0,0>, v=< 1,0,0>, a=< 0,0,0>             (0)(1)(2)      (3)   
p=< 2,0,0>, v=<-1,0,0>, a=< 0,0,0>

p=< 0,0,0>, v=< 3,0,0>, a=< 0,0,0>    
p=< 0,0,0>, v=< 2,0,0>, a=< 0,0,0>    -6 -5 -4 -3 -2 -1  0  1  2  3
p=< 0,0,0>, v=< 1,0,0>, a=< 0,0,0>                       X (3)      
p=< 1,0,0>, v=<-1,0,0>, a=< 0,0,0>

------destroyed by collision------    
------destroyed by collision------    -6 -5 -4 -3 -2 -1  0  1  2  3
------destroyed by collision------                      (3)         
p=< 0,0,0>, v=<-1,0,0>, a=< 0,0,0>
```

In this example, particles 0, 1, and 2 are simultaneously destroyed at the time and place marked X. On the next tick, particle 3 passes through unharmed.

How many particles are left after all collisions are resolved?

In [17]:
def _test_input2():
    return process_points(StringIO(dedent("""\
        p=<-6,0,0>, v=< 3,0,0>, a=< 0,0,0>
        p=<-4,0,0>, v=< 2,0,0>, a=< 0,0,0>
        p=<-2,0,0>, v=< 1,0,0>, a=< 0,0,0>
        p=< 3,0,0>, v=<-1,0,0>, a=< 0,0,0>
        """)))
TEST_INPUT2 = _test_input2()

In [13]:
np.arange(5).reshape((-1, 1)).repeat(3, axis=1)

array([[0, 0, 0],
       [1, 1, 1],
       [2, 2, 2],
       [3, 3, 3],
       [4, 4, 4]])

In [14]:
def pos_over_t(point: Point, time_arr: np.array) -> np.array:
    time_arr = time_arr.reshape((-1, 1)).repeat(3, axis=1)
    
    pos = np.int_(point.pos)
    vel = np.int_(point.vel)
    acc = np.int_(point.acc)
    
    vel_over_t = np.empty((time_arr.shape[0] + 1, 3), dtype=np.int_)
    vel_over_t[0, :] = 0
    vel_over_t[1:, :] = (acc * time_arr + vel).cumsum(axis=0)
    return pos + vel_over_t

In [16]:
pos_over_t(TEST_INPUT[1], np.arange(1, 5))

array([[  4,   0,   0],
       [  2,   0,   0],
       [ -2,   0,   0],
       [ -8,   0,   0],
       [-16,   0,   0]])

In [18]:
a = np.bool_([[True, True], [False, True]])

In [19]:
a[0, :] & a[1, :]

array([False,  True], dtype=bool)

In [20]:
np.logical_and(a[0, :], a[1, :])

array([False,  True], dtype=bool)

In [55]:
from scipy.spatial.distance import pdist, squareform

In [62]:
def resolve_collisions(point_dict: Dict[int, np.int_], time: int) -> Set[int]:
    """
    Resolve collisions between points given arrays of point positions over time.
    
    """
    uncollided = set(point_dict.keys())
    
    for t in range(time + 1):
        collided = set()
        
        uncollided_arr = np.empty((len(uncollided), 3), dtype=np.int_)
        uncollided_map = {}
        for i, p in enumerate(uncollided):
            uncollided_map[i] = p
            uncollided_arr[i, :] = point_dict[p][t, :]
        
        dists = squareform(pdist(uncollided_arr, metric='cityblock'))
        uncollided.difference_update(
            uncollided_map[i] 
            for i in itertools.chain.from_iterable(
                pair for pair in zip(*np.where(dists == 0)) if pair[0] != pair[1]))
    
    return uncollided

In [30]:
def collisions_setup(points: list, max_t: int) -> Set[int]:
    time_arr = np.arange(1, max_t + 1)
    point_dict = {p.id_: pos_over_t(p, time_arr) for p in points}
    return resolve_collisions(point_dict, max_t)

In [64]:
assert collisions_setup(TEST_INPUT, 3) == {0, 1}
assert collisions_setup(TEST_INPUT2, 3) == {3}

In [66]:
%%time
result = collisions_setup(PUZZLE_INPUT, 100000)

CPU times: user 3min 56s, sys: 4.69 s, total: 4min 1s
Wall time: 4min 2s


In [67]:
len(result)

504